DROP TABLE IF EXISTS activity_laps;
DROP TABLE IF EXISTS activity_splits;
ALTER TABLE activities DROP COLUMN IF EXISTS sport_type;
ALTER TABLE activities DROP COLUMN IF EXISTS elapsed_time;
ALTER TABLE activities DROP COLUMN IF EXISTS average_speed;
ALTER TABLE activities DROP COLUMN IF EXISTS max_speed;
ALTER TABLE activities DROP COLUMN IF EXISTS average_temp;
ALTER TABLE activities DROP COLUMN IF EXISTS weighted_average_watts;
ALTER TABLE activities DROP COLUMN IF EXISTS max_watts;
ALTER TABLE activities DROP COLUMN IF EXISTS kilojoules;
ALTER TABLE activities DROP COLUMN IF EXISTS elev_high;
ALTER TABLE activities DROP COLUMN IF EXISTS elev_low;
ALTER TABLE activities DROP COLUMN IF EXISTS suffer_score;
ALTER TABLE activities DROP COLUMN IF EXISTS pr_count;
ALTER TABLE activities DROP COLUMN IF EXISTS workout_type;
ALTER TABLE activities DROP COLUMN IF EXISTS device_name;
ALTER TABLE activities DROP COLUMN IF EXISTS gear_name;
ALTER TABLE activities DROP COLUMN IF EXISTS start_lat;
ALTER TABLE activities DROP COLUMN IF EXISTS start_lng;
ALTER TABLE activities DROP COLUMN IF EXISTS map_summary_polyline;
