-- Generalizes the Todoist task tables so several task sources share them.
--
-- Vikunja joins Todoist as a second task provider. Productivity analytics reads
-- every task from one pair of tables instead of a UNION per provider, so the
-- tables lose the todoist_ prefix and gain a source column, the way habits,
-- biometrics and nutrition_daily already discriminate their providers.
ALTER TABLE todoist_tasks RENAME TO tasks;
ALTER TABLE todoist_task_completions RENAME TO task_completions;

ALTER TABLE tasks ADD COLUMN source VARCHAR(50);
UPDATE tasks SET source = 'todoist';
ALTER TABLE tasks ALTER COLUMN source SET NOT NULL;

ALTER TABLE task_completions ADD COLUMN source VARCHAR(50);
UPDATE task_completions SET source = 'todoist';
ALTER TABLE task_completions ALTER COLUMN source SET NOT NULL;

-- External ids are only unique within a provider: a Vikunja task id is a small
-- integer and could collide with a Todoist one. The old unique keys were
-- generated by Postgres and one of them hit the 63-byte identifier limit, so
-- they are looked up rather than named.
DO $$
DECLARE
    unique_constraint RECORD;
BEGIN
    FOR unique_constraint IN
        SELECT conrelid::regclass AS table_name, conname
        FROM pg_constraint
        WHERE conrelid IN ('tasks'::regclass, 'task_completions'::regclass)
            AND contype = 'u'
    LOOP
        EXECUTE format('ALTER TABLE %s DROP CONSTRAINT %I',
            unique_constraint.table_name, unique_constraint.conname);
    END LOOP;
END $$;

ALTER TABLE tasks
    ADD CONSTRAINT tasks_user_source_external_key
    UNIQUE (user_id, source, external_id);
ALTER TABLE task_completions
    ADD CONSTRAINT task_completions_user_source_task_completed_key
    UNIQUE (user_id, source, task_external_id, completed_at);

ALTER INDEX idx_todoist_tasks_user_active RENAME TO idx_tasks_user_active;
ALTER INDEX idx_todoist_tasks_user_due_date RENAME TO idx_tasks_user_due_date;
ALTER INDEX idx_todoist_tasks_user_due_at RENAME TO idx_tasks_user_due_at;
ALTER INDEX idx_todoist_tasks_user_added_at RENAME TO idx_tasks_user_added_at;
ALTER INDEX idx_todoist_task_completions_user_completed_at
    RENAME TO idx_task_completions_user_completed_at;
ALTER INDEX idx_todoist_task_completions_user_task
    RENAME TO idx_task_completions_user_task;

ALTER INDEX todoist_tasks_pkey RENAME TO tasks_pkey;
ALTER INDEX todoist_task_completions_pkey RENAME TO task_completions_pkey;
ALTER TABLE tasks RENAME CONSTRAINT todoist_tasks_user_id_fkey TO tasks_user_id_fkey;
ALTER TABLE task_completions
    RENAME CONSTRAINT todoist_task_completions_user_id_fkey TO task_completions_user_id_fkey;

COMMENT ON COLUMN tasks.source IS 'Task provider: todoist or vikunja.';
COMMENT ON COLUMN task_completions.source IS 'Task provider: todoist or vikunja.';
