---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: ghcr-secret
  namespace: life-dashboard
spec:
  encryptedData:
    .dockerconfigjson: AgCmydMGAazfSWuqI2lTg4H/zmg3ls7P9TsnrGBTyYpyQT7/HgvxQD9VAYcMQMGDfuuO2RPdjUeO9kkJDQFg/fJiTq7lzv3M5WwE6Z22TGWkAChYr03In/vsK6DxeTLfu6R6EowgWLoPlmY8OpxizNJAsa2XM9rZsqIrBrTA3FiYv0nKn3FW4kE5RUQgezw/ews1R9yX4JGlyXf9uo4wTQHVFBLROUCPwWf9FuaFaKm1IpjiTdc1TVT/srOizfm98TCPj4U8U3vrLfR3LMamS8HO6RERJGzsT9yYycUq4mynZYaxkJvVIo4P6hwMPfZgu5FcFz1mPXkQcpuC40TYrOemCGHPMrtuiG68r8cweGastVYLUo/NMg3mjI0vHwnlJBd5a/dn/1bjWWBjdhz+Kb1kbTKziAlUXggd1MbsXI0XvUpiFib48ljzsJz5ankSoMiAqoCT2MlaoQy4K1sEelst0KA2ZjyvuDHwm5Q8gebH9+Bd1ta7hoq5I56f4Rmijy3rRlWkS2sziuOJKelc9LN/oRFlvIHc6BD70H5ahJcwAEWSKzBxHPoQwnWIwz1aaUDvGJBdPDTXHijBPJ/bRRksA+Wd17hOryQtzomomBVmBGiJH40e2WeYGAAAB//sWVarddmhn53gPjulhqttI0W2hH4zbnmCa6zn1CLN5k7Oasyw0ORXij4HSxdEFd23qpv/Bx9aqnNjnxQHKzm1AV9Wme9fDADxEWEPjDQ33tfjJyLS/5Ni+QMVfGtDQA8QDTtJNn5r3nTH2IRQalhZJMSJVugEF+Sg5AnrkBJ0uwqKM8ItI5qUyrNAwKns8xBQpGVHPG/naH6tzXli6k5rHV3phtUXev4qkKtjDV8BFBtl7TndZ7SfrHArX/2rrDXP8QuXbyr0eTCbiNrMz4kCAW/KOv0s28msJotefvHs
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: ghcr-secret
      namespace: life-dashboard
    type: kubernetes.io/dockerconfigjson
