apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: life-dashboard

resources:
- ../../base
- ingress.yaml
- postgres-sealed.yaml
- ghcr-sealed.yaml
- app-config-sealed.yaml
- servicemonitor.yaml
- prometheusrule.yaml
- grafana-dashboard.yaml

images:
- name: backend
  newName: ghcr.io/jaennil/life-dashboard/backend
  newTag: 703d3f6ece8d138a46767d8827625b0d6289ae79
- name: frontend
  newName: ghcr.io/jaennil/life-dashboard/frontend
  newTag: 703d3f6ece8d138a46767d8827625b0d6289ae79
