apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: life-dashboard

resources:
- ../../base
- ingress.yaml
- postgres-sealed.yaml
- ghcr-sealed.yaml
- app-config-sealed.yaml
- servicemonitor.yaml
- prometheusrule.yaml
- grafana-dashboard.yaml

images:
- name: backend
  newName: ghcr.io/jaennil/life-dashboard/backend
  newTag: acfb8a450b190d2b0e16398cbeec0a63fe3ba8f7
- name: frontend
  newName: ghcr.io/jaennil/life-dashboard/frontend
  newTag: acfb8a450b190d2b0e16398cbeec0a63fe3ba8f7
